---
- name: update shared files
  sudo_user: deployer
  template: src={{ item }} dest={{ rails_app_shared_path }}/config/{{ item }}
  with_items:
    - database.yml
    - secrets.yml

- name: mina | create deploy directory
  sudo_user: deployer
  file: path=~/deploy/ state=directory

- name: mina | copy deploy.rb script
  sudo_user: deployer
  template: src=mina_deploy.rb dest=~/deploy/deploy.rb

- name: mina | generate bash script
  sudo_user: deployer
  shell: >
    executable=/bin/bash source /etc/profile;
    chruby `cat ~/.ruby-version` &&
    mina -S -f ~/deploy/deploy.rb deploy | grep -v "Elapsed" > ~/deploy/deploy.sh &&
    chmod +x ~/deploy/deploy.sh

- name: mina | execute bash script
  sudo_user: deployer
  shell: >
    /bin/bash ~/deploy/deploy.sh

- name: capture rails app ruby path
  sudo_user: deployer
  shell: >
    executable=/bin/bash source /etc/profile;
    chruby `cat ~/.ruby-version` &&
    which ruby
  register: rails_app_ruby_path
  when: "rails_app_nginx_group in group_names"

- name: update nginx site config
  template: src=nginx_site.conf dest=/etc/nginx/sites-enabled/{{ rails_app_name }}_{{ rails_app_env }}.conf
  notify: restart nginx
  when: "rails_app_nginx_group in group_names"
